nelmio_alice:
    loading_limit: 5 # Alice may do some recursion to resolve certain values.
                     # This parameter defines a limit which will stop the
                     # resolution once reached.
    max_unique_values_retry: 150 # Maximum number of time Alice can try to
                                   # generate a unique value before stopping and
                                   # failing.
    locale: 'en_US' # Default locale for the Faker Generator
    seed: 1 # Value used to make sure Faker generates data consistently across
            # runs, set to null to disable.
    functions_blacklist:
        - 'current'
        - 'shuffle'
        - 'date'
        - 'time'
        - 'file'
        - 'md5'
        - 'sha1'
